[build]
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/app-ads.txt"
  to = "/app-ads.txt"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

